name: EssentialsMagic
version: '1.0-SNAPSHOT'
main: essentialsmagic.EssentialsMagic.main
api-version: '1.20'
authors: [ GabrielBitello ]
description: A essentials plugin
depend: [Oraxen]
commands:
  magicfire:
    aliases: [mf]
    description: Comando principal do MagicFire
    usage: /<command> <subcommand>
  magickey:
    aliases: [mk]
    description: Comando principal do MagicKey
    usage: /<command> <subcommand>
  setspawn:
    description: "Define o local de spawn."
    usage: "/setspawn"
    permission: "EssentialsMagic.SetSpawn"
  spawn:
    description: "Teleporta para o local de spawn."
    usage: "/spawn"
    permission: "EssentialsMagic.Spawn"
  home:
    description: "Comando para definir e teleportar para a home."
    usage: "/home [set]"
    permission: "EssentialsMagic.Home"
